# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HUAWEI Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HUAWEI Wallet
  pod 'Charts'
  pod 'TinyConstraints'

end
